# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
description: >
  Staffed by community leaders that are passionate about coalescing the
  technology scene in Sacramento, we support our area's usergroups, conferences,
  and most importantly, people, through mentoring, financial support, training,
  and logistics.
title: Techramento

# Social
email:
facebook_username: techramento
github_username: techramento
twitter_username: TechramentoCA
url: "http://techramento.org"

# Legal Information
legal_title: Techramento

corporate_mailing_address_1: 9633 Spring Breeze Ct.
corporate_mailing_address_2:
corporate_mailing_city: Elk Grove
corporate_mailing_state: CA
corporate_mailing_postal_code: 95757

corporate_physical_address_1: 9633 Spring Breeze Ct.
corporate_physical_address_2:
corporate_physical_city: Elk Grove
corporate_physical_state: CA
corporate_physical_postal_code: 95757

# Build settings
markdown: kramdown
