# Site settings
title: Techramento
legal_title: Techramento
email:
description: >
  Staffed by community leaders that are passionate about coalescing the
  technology scene in Sacramento, we support our area's usergroups, conferences,
  and most importantly, people, through mentoring, financial support, training,
  and logistics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://techramento.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: techramento
facebook_username: techramento
corporate_physical_address_1: 1715 I St.
corporate_physical_address_2:
corporate_physical_city: Sacramento
corporate_physical_state: CA
corporate_physical_postal_code: 95811
corporate_mailing_address_1: 1715 I St.
corporate_mailing_address_2:
corporate_mailing_city: Sacramento
corporate_mailing_state: CA
corporate_mailing_postal_code: 95811

# Build settings
markdown: kramdown
